__default__:
    partition: core
    cpus_per_task: 1
    ntasks: 1
    time: 60
    mem: 2000
    job_name: "{rule}.{wildcards}"
    output: "logs/{rule}.{wildcards}.%j.out"
    error: "logs/{rule}.{wildcards}.%j.err"

compress_fastaq:
    output: "logs/{rule}.%j.out"
    error: "logs/{rule}.%j.err"

gpu_basecalling:
    partition: gpu
    time: 360
    mem: 30000
    gres: gpu:0
    ntasks: 12
