__default__:
    partition: core
    cpus_per_task: 1
    ntasks: 1
    time: 60
    mem: 2000
    job_name: "{rule}.{wildcards}"
    output: "logs/{rule}.{wildcards}.%j.out"
    error: "logs/{rule}.{wildcards}.%j.err"

basecalling:
    partition: nolimit
    time: 14400
    ntasks: 8
    cpus_per_task: 4
    time: 2880

